# Generated by Django 2.1 on 2018-08-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180817_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.Person'),
        ),
    ]
