# Generated by Django 2.1 on 2018-08-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180817_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='timestamp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=100),
        ),
    ]
