# Generated by Django 2.1 on 2018-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180918_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='value',
            field=models.IntegerField(default=99),
        ),
    ]
